Update uptime.yml

diff --git a/.github/workflows/uptime.yml b/.github/workflows/uptime.yml
--- a/.github/workflows/uptime.yml
+++ b/.github/workflows/uptime.yml
@@ -8,29 +8,24 @@ on:
 jobs:
   check_urls:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        url:
+          - "https://toilet.football"
+          - "https://new.toilet.football"
+          - "https://winokan.com"
+          - "https://foosball.winokan.com"
+          - "https://fragalysis.diamond.ac.uk"
+    
+    name: Check ${{ matrix.url }}  # This makes each job name unique
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Check URLs
+      - name: Check URL
         run: |
-          urls=(
-            "https://toilet.football"
-            "https://new.toilet.football"
-            "https://winokan.com"
-            "https://foosball.winokan.com"
-          )
+          echo "Checking ${{ matrix.url }}..."
+          status_code=$(curl -o /dev/null -s -w "%{http_code}" "${{ matrix.url }}")
+          if [[ "$status_code" -ne 200 ]]; then
+            echo "::error title=URL Check Failed::URL ${{ matrix.url }} returned status $status_code"
+            exit 1
+          fi
 
-          for url in "${urls[@]}"; do
-            echo "Checking $url..."
-            status_code=$(curl -o /dev/null -s -w "%{http_code}" "$url")
-            if [[ "$status_code" -ne 200 ]]; then
-              echo "::error title=URL Check Failed::URL $url returned status $status_code"
-              exit 1
-            fi
-          done
-
-      - name: Success Message
-        if: success()
-        run: echo "All URLs returned 200 OK!"
